{
 "title": "Logs",
 "time": { "from": "2024-04-24T23:06:43.180Z", "to": "2024-04-25T11:06:43.180Z" },
 "panels": [
  {
   "title": "loki",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"loki\"} |= ``"
    }
   ]
  },
  {
   "title": "API-Gateway",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"api-gateway\"} |= ``"
    }
   ]
  },
  {
   "title": "Symptom-API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"symptom-api\"} |= ``"
    }
   ]
  },
  {
   "title": "Patient-API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"patient-api\"} |= ``"
    }
   ]
  }
 ]
}